# Generated by Django 5.1.4 on 2025-01-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_share', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='photo',
            new_name='image',
        ),
    ]
